language: cpp
compiler:
  - clang
  - gcc
install:
  ########################
  # Install a recent CMake
  ########################
  - |
    if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    fi
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
 - ./build.sh
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake