sudo: required
dist: trusty
language: generic
before_install:
  # Install Linuxbrew
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew update
  - brew --version
  # Install Buck
  - brew tap facebook/fb
  - travis_wait brew install buck
  - buck --version
script:
  - travis_wait buck build :odict
cache:
  directories:
    - $HOME/.linuxbrew/